[package]
name = "shoe"
version = "0.8.15"
edition = "2021"

[dependencies]
copypasta = "0.10.1"
crossterm = "0.28.1"
ctrlc = "3.4.5"
meval = { git = "https://github.com/Titaniumtown/meval-rs.git" }
relative-path = "1.9.3"
shellexpand = "3.1.0"
strip-ansi-escapes = "0.2.1"
